### ISSUE TITLE
🐛 New Bug: Client-side exception has occurred while uploading testng-results.xml File 

### ISSUE THREAD

**Issue by Mitesh411** [WasiqB/ultra-reporter-app#17]
### ❓ What is the bug?

Application error: a client-side exception has occurred (see the browser console for more information).

### 📃 Steps to reproduce the bug

Please Go throuugh the **JAM** Video which Consists of Console and Network log for more details

https://jam.dev/c/2658cf3c-e8f6-4f5f-bdce-99909ac79c17

[testng-results.zip](https://github.com/user-attachments/files/17179978/testng-results.zip)

### ✅ Expected Behavior

-> Upload testng-results.xml from the test-output folder
-> Wait for the beautiful Test reports to get generated

### ❌ Actual Behavior

**Application error: a client-side exception has occurred (see the browser console for more information).**

Error Message is Displayed to User

**Comment by WasiqB** [comment]
@Mitesh411 , Thanks for raising the issue. I will fix this issue soon.

**Comment by WasiqB** [comment]
@Mitesh411 , issue has been fixed, please check again in few mins.
